id: P4EF66FCF
initial_creation_type: ocr
source_metadata:
  volumes:
    956a34612a374c7184f4e6e08e200cf3:
      base_file: v070.txt
      image_group_id: I1PD95915
      title: མདོ་སྡེའི་རྒྱན་གྱི་བཤད་པ།
      total_pages: 1505
      volume_number: 70
