id: P4EF66FCF
initial_creation_type: ocr
source_metadata:
  volumes:
    bd7b7d6443624d8f91e1ecc830153303:
      base_file: v070.txt
      image_group_id: I1PD95915
      title: མདོ་སྡེའི་རྒྱན་གྱི་བཤད་པ།
      total_pages: 1505
      volume_number: 70
